In [2]:
import numpy as np

# numpy의 행렬

1. np.matrix: 수학
2. np.array: 머신러닝

### matrix 생성

In [2]:
A = np.matrix('1,2,3,4 ; 5,6,7,8 ; 9,10,11,12')
x = np.matrix('1;2;3;4')
print(A)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]
 [4]]


### array 생성

In [4]:
A = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9, 10, 11, 12]
])
x = np.array([
    [1],
    [2],
    [3],
    [4]
])
print(A)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]
 [4]]


## 행렬 곱셈
- 행렬의 덧셈은 별게 없어서... 
- 그냥 넘어 갈게요 

### 행렬 / 벡터 곱

$$
    \begin{bmatrix}
        a_{11} & a_{12} & a_{13} \\
        a_{21} & a_{22} & a_{23} \\
        a_{31} & a_{32} & a_{33} \\
    \end{bmatrix}
    \begin{bmatrix}
        x_1 \\
        x_2 \\
        x_3 \\
        x_4
    \end{bmatrix} = 
    \begin{bmatrix}
        a_{11} \cdot x_1 + a_{12} \cdot x_2 + a_{13} \cdot x_3 \\
        a_{21} \cdot x_1 + a_{22} \cdot x_2 + a_{23} \cdot x_3 \\
        a_{31} \cdot x_1 + a_{32} \cdot x_2 + a_{33} \cdot x_3 \\
    \end{bmatrix}
$$

### 행렬 / 벡터 곱 - 첫번째 - 01
- 손으로 계산해보기

$$
    \begin{bmatrix}
            1 & 4 & 2 & 0 \\
            9 & 5 & 0 & 0 \\
            4 & 0 & 2 & 4 \\
            6 & 1 & 8 & 3 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    \begin{bmatrix}
            1 \cdot 1 + 4 \cdot 2 + 2 \cdot 3 + 0 \cdot 4 \\
            9 \cdot 1 + 5 \cdot 2 + 0 \cdot 3 + 0 \cdot 4 \\
            4 \cdot 1 + 0 \cdot 2 + 2 \cdot 3 + 4 \cdot 4 \\
            6 \cdot 1 + 1 \cdot 2 + 8 \cdot 3 + 3 \cdot 4 \\
    \end{bmatrix}
$$

- 정답 확인해보기

$$
    \begin{bmatrix}
            1 & 4 & 2 & 0 \\
            9 & 5 & 0 & 0 \\
            4 & 0 & 2 & 4 \\
            6 & 1 & 8 & 3 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    \begin{bmatrix}
            15 \\
            19 \\
            26 \\
            44 \\
    \end{bmatrix}
$$


### 행렬 / 벡터 곱 - 첫번째 - 02
- 손으로 계산해보기

$$
    \begin{bmatrix}
            4 & 5 & 2 & 1 \\
            2 & 3 & 8 & 0 \\
            1 & 0 & 7 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    ?
$$

- 정답 확인해보기

$$
    \begin{bmatrix}
            4 & 5 & 2 & 1 \\
            2 & 3 & 8 & 0 \\
            1 & 0 & 7 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    \begin{bmatrix}
            24 \\
            32 \\
            30 \\
    \end{bmatrix}
$$


### 행렬/벡터 곱 - 두번째 

In [16]:
A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4; 6,1,8,3')
x = np.matrix('1;2;3;4')
b = np.zeros((4,1))
n = 4

# todo martix를 이용한 행렬곱 결과를 출력 
for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        # TODO
        val += A[i,j] * x[j,0]
    b[i] = val
print(b)

[[15.]
 [19.]
 [26.]
 [44.]]


In [18]:
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n= 4

for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        # TODO
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[15 19 26 44]


### 행렬/벡터 곱 - 세번째

In [20]:
A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4; 6,1,8,3')
x = np.matrix('1;2;3;4')

print(A)
print(x)

b = A * x
print(b)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[[1]
 [2]
 [3]
 [4]]
[[15]
 [19]
 [26]
 [44]]


In [26]:
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])

print(A)
print(x)

# b = A * x
b = np.dot(A, x)
print(b)

b = np.matmul(A, x)
print(b)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[1 2 3 4]
[15 19 26 44]
[15 19 26 44]


### 행렬 / 벡터 곱 - 복습

$$
    \begin{bmatrix}
            4 & 5 & 2 & 1 \\
            2 & 3 & 8 & 0 \\
            1 & 0 & 7 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    ?
$$

In [3]:
A = np.matrix('4, 5, 2, 1; 2, 3, 8, 0; 1, 0, 7, 2')
x = np.matrix('1;2;3;4')

In [5]:
# for loop를 이용한 행렬/벡터 곱 구현

b = np.zeros((3,1))
#TODO
for i in range(3):
    val = 0.0
    for j in range(4):
        val += A[i,j] * x[j,0]
    b[i] = val
print(b)

[[24.]
 [32.]
 [30.]]


In [7]:
# matrix 타입의 행렬/벡터 곱 구현
b = A * x
print(b)

[[24]
 [32]
 [30]]


In [12]:
A = np.array([[4, 5, 2, 1], [2, 3, 8, 0], [1, 0, 7, 2]])
x = np.array([1,2,3,4])

In [15]:
# for loop를 이용한 행렬/벡터 곱 구현

b = np.zeros(3)
# TODO
for i in range(3):
    val = 0
    for j in range(4):
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[24. 32. 30.]


In [10]:
# array 타입의 행렬/벡터 곱 구현

b = np.dot(A, x)
print(b)

b = np.matmul(A, x)
print(b)

[24 32 30]
[24 32 30]
