In [2]:
import numpy as np

# numpy의 행렬

1. np.matrix: 수학
2. np.array: 머신러닝

### matrix 생성

In [2]:
A = np.matrix('1,2,3,4 ; 5,6,7,8 ; 9,10,11,12')
x = np.matrix('1;2;3;4')
print(A)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]
 [4]]


### array 생성

In [4]:
A = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9, 10, 11, 12]
])
x = np.array([
    [1],
    [2],
    [3],
    [4]
])
print(A)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]
 [4]]


### ndarray 기본 연산자
- add, substract, multiply, divide

In [3]:
x = np.random.randint(10, size = (4,3))
y = np.random.randint(10, size = (4,3))
print(x)
print(y)

[[1 8 7]
 [3 1 1]
 [2 7 3]
 [7 3 0]]
[[0 8 1]
 [9 0 3]
 [5 9 6]
 [4 9 7]]


In [4]:
np.add(x, y)

array([[ 1, 16,  8],
       [12,  1,  4],
       [ 7, 16,  9],
       [11, 12,  7]])

In [5]:
np.divide(x,y)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 7.        ],
       [0.33333333,        inf, 0.33333333],
       [0.4       , 0.77777778, 0.5       ],
       [1.75      , 0.33333333, 0.        ]])

In [6]:
x + y

array([[ 1, 16,  8],
       [12,  1,  4],
       [ 7, 16,  9],
       [11, 12,  7]])

In [9]:
# 행렬 곱셈 아님!!!
np.multiply(x, y)

array([[ 0, 64,  7],
       [27,  0,  3],
       [10, 63, 18],
       [28, 27,  0]])

In [10]:
# 행렬곱셈 아님!!!
x * y

array([[ 0, 64,  7],
       [27,  0,  3],
       [10, 63, 18],
       [28, 27,  0]])

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a_list = [1,2,3]
b_list = [4,5,6]

In [24]:
a + b

array([5, 7, 9])

In [28]:
a_list + b_list

[1, 2, 3, 4, 5, 6]

In [25]:
a == 1

array([ True, False, False])

In [29]:
a_list == b_list

False

In [26]:
b < 5

array([ True, False, False])

In [30]:
a_list < b_list

True

## 행렬 곱셈(내적)
- 행렬의 덧셈은 별게 없어서... 
- 그냥 넘어 갈게요 

### 행렬 / 벡터 곱

$$
    \begin{bmatrix}
        a_{11} & a_{12} & a_{13} & a_{14} \\
        a_{21} & a_{22} & a_{23} & a_{24} \\
        a_{31} & a_{32} & a_{33} & a_{34} \\
    \end{bmatrix}
    \begin{bmatrix}
        x_1 \\
        x_2 \\
        x_3 \\
        x_4
    \end{bmatrix} = 
    \begin{bmatrix}
        a_{11} \cdot x_1 + a_{12} \cdot x_2 + a_{13} \cdot x_3 + a_{14} \cdot x_4 \\
        a_{21} \cdot x_1 + a_{22} \cdot x_2 + a_{23} \cdot x_3 + a_{24} \cdot x_4 \\
        a_{31} \cdot x_1 + a_{32} \cdot x_2 + a_{33} \cdot x_3 + a_{34} \cdot x_4 \\
    \end{bmatrix}
$$

### 행렬 / 벡터 곱 - 첫번째 - 01
- 손으로 계산해보기

$$
    \begin{bmatrix}
            1 & 4 & 2 & 0 \\
            9 & 5 & 0 & 0 \\
            4 & 0 & 2 & 4 \\
            6 & 1 & 8 & 3 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    \begin{bmatrix}
            1 \cdot 1 + 4 \cdot 2 + 2 \cdot 3 + 0 \cdot 4 \\
            9 \cdot 1 + 5 \cdot 2 + 0 \cdot 3 + 0 \cdot 4 \\
            4 \cdot 1 + 0 \cdot 2 + 2 \cdot 3 + 4 \cdot 4 \\
            6 \cdot 1 + 1 \cdot 2 + 8 \cdot 3 + 3 \cdot 4 \\
    \end{bmatrix}
$$

- 정답 확인해보기

$$
    \begin{bmatrix}
            1 & 4 & 2 & 0 \\
            9 & 5 & 0 & 0 \\
            4 & 0 & 2 & 4 \\
            6 & 1 & 8 & 3 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    \begin{bmatrix}
            15 \\
            19 \\
            26 \\
            44 \\
    \end{bmatrix}
$$


### 행렬 / 벡터 곱 - 첫번째 - 02
- 손으로 계산해보기

$$
    \begin{bmatrix}
            4 & 5 & 2 & 1 \\
            2 & 3 & 8 & 0 \\
            1 & 0 & 7 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    ?
$$

- 정답 확인해보기

$$
    \begin{bmatrix}
            4 & 5 & 2 & 1 \\
            2 & 3 & 8 & 0 \\
            1 & 0 & 7 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    \begin{bmatrix}
            24 \\
            32 \\
            30 \\
    \end{bmatrix}
$$


### 행렬/벡터 곱 - 두번째 

In [16]:
A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4; 6,1,8,3')
x = np.matrix('1;2;3;4')
b = np.zeros((4,1))
n = 4

# todo martix를 이용한 행렬곱 결과를 출력 
for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        # TODO
        val += A[i,j] * x[j, 0]
    b[i] = val
print(b)

[[15.]
 [19.]
 [26.]
 [44.]]


In [18]:
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n= 4

for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        # TODO
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[15 19 26 44]


### 행렬/벡터 곱 - 세번째

In [20]:
A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4; 6,1,8,3')
x = np.matrix('1;2;3;4')

print(A)
print(x)

b = A * x
print(b)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[[1]
 [2]
 [3]
 [4]]
[[15]
 [19]
 [26]
 [44]]


In [26]:
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])

print(A)
print(x)

# b = A * x
b = np.dot(A, x)
print(b)

b = np.matmul(A, x)
print(b)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[1 2 3 4]
[15 19 26 44]
[15 19 26 44]


### 행렬 / 벡터 곱 - 복습

$$
    \begin{bmatrix}
            4 & 5 & 2 & 1 \\
            2 & 3 & 8 & 0 \\
            1 & 0 & 7 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    ?
$$

In [3]:
A = np.matrix('4, 5, 2, 1; 2, 3, 8, 0; 1, 0, 7, 2')
x = np.matrix('1;2;3;4')

In [5]:
# for loop를 이용한 행렬/벡터 곱 구현

b = np.zeros((3,1))
#TODO
for i in range(3):
    val = 0.0
    for j in range(4):
        val += A[i,j] * x[j,0]
    b[i] = val
print(b)

[[24.]
 [32.]
 [30.]]


In [7]:
# matrix 타입의 행렬/벡터 곱 구현
b = A * x
print(b)

[[24]
 [32]
 [30]]


In [12]:
A = np.array([[4, 5, 2, 1], [2, 3, 8, 0], [1, 0, 7, 2]])
x = np.array([1,2,3,4])

In [15]:
# for loop를 이용한 행렬/벡터 곱 구현

b = np.zeros(3)
# TODO
for i in range(3):
    val = 0
    for j in range(4):
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[24. 32. 30.]


In [10]:
# array 타입의 행렬/벡터 곱 구현

b = np.dot(A, x)
print(b)

b = np.matmul(A, x)
print(b)

[24 32 30]
[24 32 30]


### 행렬과 벡터의 곱만 확인 - 다른 형태의 연산도 확인
- 내적(inner product/dot product)으로 제외한 행렬/벡터의 연산은 
- 행렬/벡터 내의 모든 원소에 대한 반복적인 연산(+, -, *, /)
- 행렬/벡터 끼리 연산을 하는 경우 두 피연산자의 크기가 같아야 한다.

#### 스칼라와 벡터의 연산
- 크기가 다른 피 연산자의 연산인 경우 
- 크기가 작은 피연산자를 반복 확장하여 크기가 큰 피연산자의 크기를 맞춘 후에 연산을 적용

In [7]:
vector = np.random.randint(10, size=(6,))
print(vector)

print(10 * vector) # 브로드 캐스팅

scalarVector = np.full((6,), 10)
print(scalarVector)
print(scalarVector * vector)

[6 5 4 4 1 0]
[60 50 40 40 10  0]
[10 10 10 10 10 10]
[60 50 40 40 10  0]


In [9]:
print(vector)
print(10 * vector)
print(10 + vector)
print(10 - vector)

[6 5 4 4 1 0]
[60 50 40 40 10  0]
[16 15 14 14 11 10]
[ 4  5  6  6  9 10]


#### 스칼라와 행렬의 연산
- 벡터와 마찬가지로 자동으로 확장하여 행렬내의 모든 원소에 반복적으로 적용

In [13]:
arr = np.random.randint(10, size=(4,3))
print(arr)
print( 10 * arr)

[[4 4 4]
 [7 6 1]
 [8 3 0]
 [7 9 6]]
[[40 40 40]
 [70 60 10]
 [80 30  0]
 [70 90 60]]


In [12]:
print(arr)
print(10 * arr)
print(10 + arr)
print(10 - arr)

[[8 4 8]
 [4 6 0]
 [4 2 1]
 [9 4 9]]
[[80 40 80]
 [40 60  0]
 [40 20 10]
 [90 40 90]]
[[18 14 18]
 [14 16 10]
 [14 12 11]
 [19 14 19]]
[[ 2  6  2]
 [ 6  4 10]
 [ 6  8  9]
 [ 1  6  1]]


#### 벡터와 벡터의 연산

In [16]:
# 크기가 같다면 문제가 되지 않는다. 
v1 = np.random.randint(1, 10, size=(4,))
v2 = np.random.randint(1, 10, size=(4,))
print(v1)
print(v2)
print(v1 + v2)
print(v1 * v2)

[7 9 5 1]
[9 4 1 5]
[16 13  6  6]
[63 36  5  5]


In [18]:
#내적을 구한다면... 
#벡터와 벡터간의 내적은 스칼라 형태의 결과가 나온다.
np.dot(v1, v2)

109

In [19]:
# 크기가 다르다면... 
v1 = np.random.randint(1, 10, size=(3,))
v2 = np.random.randint(1, 10, size=(4,))
print(v1)
print(v2)

[3 1 9]
[4 1 1 4]


In [20]:
print(v1 + v2)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [21]:
np.dot(v1, v2)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

### inner/dot product
- 앞의 열과 뒤에 행의 갯수가 같아야만 합니다.

In [22]:
arr1 = np.matrix('1,2,3,4')
arr2 = np.matrix('1;2;3;4')
print(arr1)
print(arr2)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [23]:
arr1 * arr2 # dot product

matrix([[30]])

In [24]:
arr2 * arr1

matrix([[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16]])

In [25]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
print(arr1)
print(arr2)

[1 2 3 4]
[1 2 3 4]


In [26]:
np.dot(arr1, arr2)

30

In [34]:
print(arr1.reshape(4,1))
print(arr2.reshape(1,4))
np.dot(arr1.reshape(4,1), arr2.reshape(1,4))

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

#### 벡터와 행렬의 연산
- 크기를 행렬의 열 크기와 베턱의 행 크기가 같아야 한다. 

In [35]:
arr1 = np.random.randint(10, size=(4,))
arr2 = np.random.randint(10, size=(3,4))
print(arr1)
print(arr2)

[6 8 8 6]
[[9 7 9 8]
 [3 3 1 7]
 [0 1 3 3]]


In [38]:
# 벡터가 행렬의 크기에 맞춰서 자동으로 확장(브로드 캐스팅)
print(arr1 + arr2)
print(arr1 * arr2)

[[15 15 17 14]
 [ 9 11  9 13]
 [ 6  9 11  9]]
[[54 56 72 48]
 [18 24  8 42]
 [ 0  8 24 18]]


In [39]:
arr1 = np.random.randint(10, size=(4,))
arr2 = np.random.randint(10, size=(4,3))
print(arr1)
print(arr2)

[2 9 3 4]
[[0 7 2]
 [7 6 1]
 [5 0 6]
 [5 0 9]]


In [40]:
print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (4,) (4,3) 

#### 행렬과 행렬의 연산
- 행과 열의 갯수가 반드시 일치
- 2차원 행렬과 3차원 행렬간에도 역시 브로드 캐스팅은 됩니다. 
- 행렬의 차원이 다르면 브로드 캐스팅 역시 적용이 되는데 
- 자동으로 확장되었을 경우 모양이 일치하기만 하면 됩니다. 

In [41]:
arr1 = np.random.randint(10, size=(2,3))
arr2 = np.random.randint(10, size=(2,3))
print(arr1)
print(arr2)

In [42]:
print(arr1 + arr2)

[[ 6 10  9]
 [10 18  7]]
