In [1]:
import numpy as np

### ndarray 통계 함수
- 평균(mean), 분산(var), 중앙(median), 최대(max), 최소(min), 표준분산(std)
- axis에 대한 이해

In [11]:
print(x)

[[1 8 7]
 [3 1 1]
 [2 7 3]
 [7 3 0]]


#### 평균

In [12]:
np.mean(x)

3.5833333333333335

In [13]:
x.mean()

3.5833333333333335

#### 최대값

In [14]:
np.max(x)

8

#### 최소값

In [15]:
np.min(x)

0

#### 분산

In [17]:
np.var(x)

7.576388888888888

#### 중앙값
- 원소들을 정렬했을 때, 중앙에 오는 값

In [18]:
np.median(x)

3.0

In [27]:
arr = x.flatten()
arr.sort()
print(arr)

[0 1 1 1 2 3 3 3 7 7 7 8]


#### 표준분산

In [19]:
np.std(x)

2.7525240941522906

### ndarray 집계(aggregation) 함수
- 합(sum), 누적합(cumsum)

In [30]:
print(x)

[[1 8 7]
 [3 1 1]
 [2 7 3]
 [7 3 0]]


In [41]:
np.sum(x)

43

In [29]:
np.cumsum(x)

array([ 1,  9, 16, 19, 20, 21, 23, 30, 33, 40, 43, 43])

### any, all 함수
- any: 특정 조건을 만족하는 값이 하나라도 있으면 True
- all: 모든 원소가 조건을 만족하면 True

In [31]:
print(x)

[[1 8 7]
 [3 1 1]
 [2 7 3]
 [7 3 0]]


In [32]:
x > 5

array([[False,  True,  True],
       [False, False, False],
       [False,  True, False],
       [ True, False, False]])

In [34]:
np.any(x > 5)

True

In [35]:
np.all(x > 5)

False

In [36]:
np.all(x >= 0)

True

### where 함수
- 조건에 따라 참인 값만 선택
- 조건에 맞지 않는 경우 인자의 값을 사용

In [37]:
print(x)

[[1 8 7]
 [3 1 1]
 [2 7 3]
 [7 3 0]]


In [40]:
np.where(x > 5, x, -1)

array([[-1,  8,  7],
       [-1, -1, -1],
       [-1,  7, -1],
       [ 7, -1, -1]])

### axis(축): x축, y축
- 함수의 인자로 axis를 인자로 갖는 함수들이 존재
- 2차원 배열에서는 행, 열로 확인
- 아래의 함수들을 이용해 확인 

#### 1차원 배열의 경우

In [48]:
arr = np.random.randint(10, size=(5,))
print(arr)

[2 3 9 0 9]


In [50]:
arr.sum()

23

In [51]:
arr.sum(axis=0)

23

In [52]:
arr.sum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

#### 2차원 배열의 경우

In [67]:
np.random.seed(1)
arr = np.random.randint(10, size=(2,3))
print(arr)
print(arr.shape)

[[5 8 9]
 [5 0 0]]
(2, 3)


In [68]:
arr.sum()

27

In [72]:
# axis = 0은 행을 뜻한다. 
# 행을 기준으로 모든 열의 값을 더한다. 
arr.sum(axis=0)

array([10,  8,  9])

In [71]:
# axis = 1은 열을 뜻한다.
# 열을 기준으로 모든 행의 값을 더한다. 
arr.sum(axis=1)

array([22,  5])

In [63]:
arr.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [75]:
np.random.seed(101)
arr = np.random.randint(10, size=(2,3))
print(arr)
print(arr.shape)

[[1 6 7]
 [9 8 4]]
(2, 3)


In [76]:
arr.mean()

5.833333333333333

In [78]:
arr.mean(axis=0)

array([5. , 7. , 5.5])

In [79]:
arr.mean(axis=1)

array([4.66666667, 7.        ])