# numpy의 행렬

1. np.matrix: 수학
2. np.array: 머신러닝

In [ ]:
import numpy as np

## matrix 생성

In [ ]:
A = np.matrix('1,2,3,4 ; 5,6,7,8 ; 9,10,11,12')
x = np.matrix('1;2;3;4')
print(A)
print(x)

## array 생성

In [ ]:
A = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9, 10, 11, 12]
])
x = np.array([
    [1],
    [2],
    [3],
    [4]
])
print(A)
print(x)

## 다양한 벡터와 행렬

### 영벡터
- 모든 원소가 0인 벡터

In [2]:
np.zeros((4,1))

array([[0.],
       [0.],
       [0.],
       [0.]])

### 일벡터
- 모든 원소가 1인 벡터

In [3]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

### 정방행렬(squre matrix)
- 행과 열의 크기가 같은 행렬

In [5]:
np.random.randint(10, size=(5,5))

array([[8, 7, 5, 8, 2],
       [8, 2, 6, 8, 2],
       [2, 0, 7, 1, 2],
       [4, 9, 2, 0, 1],
       [3, 9, 9, 8, 1]])

### 대각행렬(digonal matrix)
- 행과 열이 같은 위치에 있고(대각)
- 비대각(대각 위치가 아닌/행과 열이 다른 위치)의 모든 요소가 0인 행렬

In [6]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### 항등행렬(identity matrix)
- 대각행렬 중에서도 대각위치의 값이 모두 1인 행렬

In [7]:
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Transpose(전치연산)
- 전치행렬: 행렬의 행과 열이 바뀐 행렬
- 전치행렬 표현법

$$
    \mathbb{A}^T
$$

- 벡터 표현법

$$ 
    \overrightarrow{A}, \mathbb{A}
$$

In [45]:
array = np.array([
    [1,4,2],
    [9,5,0],
    [4,0,2],
    [6,1,8]
])
array

array([[1, 4, 2],
       [9, 5, 0],
       [4, 0, 2],
       [6, 1, 8]])

In [46]:
array.T

array([[1, 9, 4, 6],
       [4, 5, 0, 1],
       [2, 0, 2, 8]])

### ndarray 기본 연산자
- add, substract, multiply, divide

In [ ]:
x = np.random.randint(10, size = (4,3))
y = np.random.randint(10, size = (4,3))
print(x)
print(y)

In [ ]:
np.add(x, y)

In [ ]:
np.divide(x,y)

In [ ]:
x + y

In [ ]:
# 행렬 곱셈 아님!!!
np.multiply(x, y)

In [ ]:
# 행렬곱셈 아님!!!
x * y

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a_list = [1,2,3]
b_list = [4,5,6]

In [ ]:
a + b

In [ ]:
a_list + b_list

In [ ]:
a == 1

In [ ]:
a_list == b_list

In [ ]:
b < 5

In [ ]:
a_list < b_list

# 타입에 따른 연산 
- 행렬/벡터 내의 모든 원소에 대한 반복적인 연산(+, -, *, /)
- 행렬/벡터 끼리 연산을 하는 경우 두 피연산자의 크기가 같아야 한다.

## 스칼라와 벡터의 연산
- 크기가 다른 피 연산자의 연산인 경우 
- 크기가 작은 피연산자를 반복 확장하여 크기가 큰 피연산자의 크기를 맞춘 후에 연산을 적용

In [ ]:
vector = np.random.randint(10, size=(6,))
print(vector)

print(10 * vector) # 브로드 캐스팅

scalarVector = np.full((6,), 10)
print(scalarVector)
print(scalarVector * vector)

In [ ]:
print(vector)
print(10 * vector)
print(10 + vector)
print(10 - vector)

#### 스칼라와 행렬의 연산
- 벡터와 마찬가지로 자동으로 확장하여 행렬내의 모든 원소에 반복적으로 적용

In [ ]:
arr = np.random.randint(10, size=(4,3))
print(arr)
print( 10 * arr)

In [ ]:
print(arr)
print(10 * arr)
print(10 + arr)
print(10 - arr)

#### 벡터와 벡터의 연산

In [ ]:
# 크기가 같다면 문제가 되지 않는다. 
v1 = np.random.randint(1, 10, size=(4,))
v2 = np.random.randint(1, 10, size=(4,))
print(v1)
print(v2)
print(v1 + v2)
print(v1 * v2)

In [ ]:
#내적을 구한다면... 
#벡터와 벡터간의 내적은 스칼라 형태의 결과가 나온다.
np.dot(v1, v2)

In [ ]:
# 크기가 다르다면... 
v1 = np.random.randint(1, 10, size=(3,))
v2 = np.random.randint(1, 10, size=(4,))
print(v1)
print(v2)

In [ ]:
print(v1 + v2)

In [ ]:
np.dot(v1, v2)

### inner/dot product
- 앞의 열과 뒤에 행의 갯수가 같아야만 합니다.

In [ ]:
arr1 = np.matrix('1,2,3,4')
arr2 = np.matrix('1;2;3;4')
print(arr1)
print(arr2)

In [ ]:
arr1 * arr2 # dot product

In [ ]:
arr2 * arr1

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
print(arr1)
print(arr2)

In [ ]:
np.dot(arr1, arr2)

In [ ]:
print(arr1.reshape(4,1))
print(arr2.reshape(1,4))
np.dot(arr1.reshape(4,1), arr2.reshape(1,4))

#### 벡터와 행렬의 연산
- 행렬의 열 크기와 벡터의 행의 크기가 같아야 한다. 

In [ ]:
arr1 = np.random.randint(10, size=(4,))
arr2 = np.random.randint(10, size=(3,4))
print(arr1)
print(arr2)

In [ ]:
# 벡터가 행렬의 크기에 맞춰서 자동으로 확장(브로드 캐스팅)
print(arr1 + arr2)
print(arr1 * arr2)

In [ ]:
arr1 = np.random.randint(10, size=(4,))
arr2 = np.random.randint(10, size=(4,3))
print(arr1)
print(arr2)

In [ ]:
print(arr1 + arr2)

#### 행렬과 행렬의 연산
- 행과 열의 갯수가 반드시 일치
- 2차원 행렬과 3차원 행렬간에도 역시 브로드 캐스팅은 됩니다. 
- 행렬의 차원이 다르면 브로드 캐스팅 역시 적용이 되는데 
- 자동으로 확장되었을 경우 모양이 일치하기만 하면 됩니다. 

In [ ]:
arr1 = np.random.randint(10, size=(2,3))
arr2 = np.random.randint(10, size=(2,3))
print(arr1)
print(arr2)

In [ ]:
print(arr1 + arr2)

# 행렬 곱셈

### 행렬 / 벡터 곱

$$
    \begin{bmatrix}
        a_{11} & a_{12} & a_{13} & a_{14} \\
        a_{21} & a_{22} & a_{23} & a_{24} \\
        a_{31} & a_{32} & a_{33} & a_{34} \\
    \end{bmatrix}
    \begin{bmatrix}
        x_1 \\
        x_2 \\
        x_3 \\
        x_4
    \end{bmatrix} = 
    \begin{bmatrix}
        a_{11} \cdot x_1 + a_{12} \cdot x_2 + a_{13} \cdot x_3 + a_{14} \cdot x_4 \\
        a_{21} \cdot x_1 + a_{22} \cdot x_2 + a_{23} \cdot x_3 + a_{24} \cdot x_4 \\
        a_{31} \cdot x_1 + a_{32} \cdot x_2 + a_{33} \cdot x_3 + a_{34} \cdot x_4 \\
    \end{bmatrix}
$$

### 행렬 / 벡터 곱 - 첫번째 - 01
- 손으로 계산해보기

$$
    \begin{bmatrix}
            1 & 4 & 2 & 0 \\
            9 & 5 & 0 & 0 \\
            4 & 0 & 2 & 4 \\
            6 & 1 & 8 & 3 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    \begin{bmatrix}
            1 \cdot 1 + 4 \cdot 2 + 2 \cdot 3 + 0 \cdot 4 \\
            9 \cdot 1 + 5 \cdot 2 + 0 \cdot 3 + 0 \cdot 4 \\
            4 \cdot 1 + 0 \cdot 2 + 2 \cdot 3 + 4 \cdot 4 \\
            6 \cdot 1 + 1 \cdot 2 + 8 \cdot 3 + 3 \cdot 4 \\
    \end{bmatrix}
$$

- 정답 확인해보기

$$
    \begin{bmatrix}
            1 & 4 & 2 & 0 \\
            9 & 5 & 0 & 0 \\
            4 & 0 & 2 & 4 \\
            6 & 1 & 8 & 3 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    \begin{bmatrix}
            15 \\
            19 \\
            26 \\
            44 \\
    \end{bmatrix}
$$


### 행렬 / 벡터 곱 - 첫번째 - 02
- 손으로 계산해보기

$$
    \begin{bmatrix}
            4 & 5 & 2 & 1 \\
            2 & 3 & 8 & 0 \\
            1 & 0 & 7 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    ?
$$

- 정답 확인해보기

$$
    \begin{bmatrix}
            4 & 5 & 2 & 1 \\
            2 & 3 & 8 & 0 \\
            1 & 0 & 7 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    \begin{bmatrix}
            24 \\
            32 \\
            30 \\
    \end{bmatrix}
$$


### 행렬/벡터 곱 - 두번째 

In [ ]:
A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4; 6,1,8,3')
x = np.matrix('1;2;3;4')
b = np.zeros((4,1))
n = 4

# todo martix를 이용한 행렬곱 결과를 출력 
for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        # TODO
        val += A[i,j] * x[j, 0]
    b[i] = val
print(b)

In [ ]:
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n= 4

for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        # TODO
        val += A[i,j] * x[j]
    b[i] = val
print(b)

### 행렬/벡터 곱 - 세번째

In [ ]:
A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4; 6,1,8,3')
x = np.matrix('1;2;3;4')

print(A)
print(x)

b = A * x
print(b)

In [ ]:
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])

print(A)
print(x)

# b = A * x
b = np.dot(A, x)
print(b)

b = np.matmul(A, x)
print(b)

### 행렬 / 벡터 곱 - 복습

$$
    \begin{bmatrix}
            4 & 5 & 2 & 1 \\
            2 & 3 & 8 & 0 \\
            1 & 0 & 7 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
            1 \\
            2 \\
            3 \\
            4 \\
    \end{bmatrix} = 
    ?
$$

In [ ]:
A = np.matrix('4, 5, 2, 1; 2, 3, 8, 0; 1, 0, 7, 2')
x = np.matrix('1;2;3;4')

In [ ]:
# for loop를 이용한 행렬/벡터 곱 구현

b = np.zeros((3,1))
#TODO
for i in range(3):
    val = 0.0
    for j in range(4):
        val += A[i,j] * x[j,0]
    b[i] = val
print(b)

In [ ]:
# matrix 타입의 행렬/벡터 곱 구현
b = A * x
print(b)

In [ ]:
A = np.array([[4, 5, 2, 1], [2, 3, 8, 0], [1, 0, 7, 2]])
x = np.array([1,2,3,4])

In [ ]:
# for loop를 이용한 행렬/벡터 곱 구현

b = np.zeros(3)
# TODO
for i in range(3):
    val = 0
    for j in range(4):
        val += A[i,j] * x[j]
    b[i] = val
print(b)

In [ ]:
# array 타입의 행렬/벡터 곱 구현

b = np.dot(A, x)
print(b)

b = np.matmul(A, x)
print(b)