In [2]:
import numpy as np

## 선형대수를 통한 해를 구하기

\begin{equation}
\begin{bmatrix}
1 & 4 & 2 & 0 \\
9 & 5 & 0 & 0 \\
4 & 0 & 2 & 4 \\
6 & 1 & 8 & 3
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
15\\19\\26\\44
\end{bmatrix}
\end{equation}

### 역행렬
- 정수: + 연산에 대해서 역원의 존재성을 보장, 하지만 * 에 대해서는 보장하지 않음
- 실수: +, * 연산에 대해서 역원의 존재성을 보장

- 행렬: 역행렬이 존재, 무조건 존재하지는 않는다. 
- 역행렬은 존재할 수도 있고, 없을수도 있다. 


### 역행열의 존재성(?)
- 반드시 정방행렬 이어야만 한다. 
- determinant(판별식) != 0 경우는 역행렬이 존재 한다!

In [18]:
A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4;6,1,8,3')
y = np.matrix('15;19;26;44')
print(A)
print(y)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[[15]
 [19]
 [26]
 [44]]


In [19]:
np.linalg.det(A)

853.9999999999995

In [20]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.15222482  0.11241218 -0.03512881  0.04683841]
 [ 0.27400468 -0.00234192  0.06323185 -0.08430913]
 [ 0.02810304 -0.05152225 -0.1088993   0.14519906]
 [ 0.1381733  -0.08665105  0.33957845 -0.11943794]]


In [27]:
# 원래 행렬에 역행렬을 곱해주면 항등행렬이 나옵니다. 
print(A * A_inv)

[[ 1.00000000e+00  0.00000000e+00 -2.77555756e-17  5.55111512e-17]
 [ 1.11022302e-16  1.00000000e+00  2.77555756e-17  0.00000000e+00]
 [ 1.11022302e-16  0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [-8.32667268e-17  8.32667268e-17 -5.55111512e-17  1.00000000e+00]]


In [30]:
A_inv * y

matrix([[1.],
        [2.],
        [3.],
        [4.]])

In [11]:
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])

y = np.array([15, 19, 26, 44])

print(A)
print(y)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[15 19 26 44]


In [31]:
np.linalg.det(A)

853.9999999999995

In [32]:
np.linalg.solve(A, y)

matrix([[1.],
        [2.],
        [3.],
        [4.]])

### 해를 구해봅시다. 
\begin{align}
x_1 + x_2 &= 2\\
2x_1 + 2x_2 &= 3
\end{align}
, that is, 
\begin{equation}
\begin{bmatrix}
1 & 1 \\
2 & 2 
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2
\end{bmatrix}=
\begin{bmatrix}
2\\3
\end{bmatrix}
\end{equation}

In [33]:
A = np.matrix('1, 1; 2, 2')
b = np.matrix('2;3')
np.linalg.det(A)

0.0

In [34]:
x = np.linalg.solve(A, b)

LinAlgError: Singular matrix

### 선형방정식 풀이법

1. 직접 풀이법(direct)
- 가우스 소거법
- ... 

2. 반복 풀이법(iteration )
- Jacobi method
- Conjucate Gradient Method -> steepest Gradient Decent(최적화)


## Jacobi Method

\begin{equation}
\begin{bmatrix}
10 & 4 & 2 & 0 \\
9 & 15 & 0 & 0 \\
4 & 0 & 12 & 4 \\
6 & 1 & 8 & 13
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
15\\19\\26\\44
\end{bmatrix}
\end{equation}

In [13]:
A = np.matrix('10,4,2,0; 9,15,0,0; 4,0,12,4;6,1,8,13')
b = np.matrix('15;19;26;44')
print(A)

[[10  4  2  0]
 [ 9 15  0  0]
 [ 4  0 12  4]
 [ 6  1  8 13]]


In [14]:
# 대각행렬을 먼저 구해 옵시다
D = np.diag(np.diag(A))
print(D)

[[10  0  0  0]
 [ 0 15  0  0]
 [ 0  0 12  0]
 [ 0  0  0 13]]


In [15]:
R = A - D
print(R)

[[0 4 2 0]
 [9 0 0 0]
 [4 0 0 4]
 [6 1 8 0]]


In [19]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[0.1        0.         0.         0.        ]
 [0.         0.06666667 0.         0.        ]
 [0.         0.         0.08333333 0.        ]
 [0.         0.         0.         0.07692308]]


$$
    x^{(k+1)} = D^{-1} (b - Rx^{(k)})
$$

In [27]:
MaxIter = 50
# x0 = np.matrix('1;1;1;1')
x0 = np.ones((4,1)) # 일벡터 

for it in range(MaxIter):
    x1 = D_inv * (b - R * x0)
    x0 = x1
print(x0)

[[1.01814882]
 [0.65577737]
 [1.09770115]
 [2.18874773]]


In [5]:
np.linalg.solve(A, y)

matrix([[1.01814882],
        [0.65577737],
        [1.09770115],
        [2.18874773]])

In [30]:
# A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4;6,1,8,3')
# b = np.matrix('15;19;26;44')
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
b = np.array([15, 19, 26, 44])
print(A)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]


In [33]:
D = np.diag(np.diag(A))
D

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [34]:
R = A - D
R

array([[0, 4, 2, 0],
       [9, 0, 0, 0],
       [4, 0, 0, 4],
       [6, 1, 8, 0]])

In [38]:
np.linalg.det(D)
D_inv = np.linalg.inv(D)
D_inv

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.2       , 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.        , 0.33333333]])

In [43]:
maxIter = 1000 
x0 = np.array([1,1,1,1])

for it in range(maxIter):
    x1 = np.dot( D_inv , (b - np.dot(R, x0)) )
    x0 = x1
print(x0)

[nan nan nan nan]


## Conjugate Gradient Method

\begin{equation}
\begin{bmatrix}
10 & 4 & 2 & 0 \\
9 & 15 & 0 & 0 \\
4 & 0 & 12 & 4 \\
6 & 1 & 8 & 13
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
15\\19\\26\\44
\end{bmatrix}
\end{equation}

In [15]:
A = np.matrix('10,4,2,0; 9,15,0,0; 4,0,12,4;6,1,8,13')
b = np.matrix('15;19;26;44')
print(A)

[[10  4  2  0]
 [ 9 15  0  0]
 [ 4  0 12  4]
 [ 6  1  8 13]]


$\alpha_k = \frac{r_k^T r_k}{p_k^T A p_k}$
$\beta_k = \frac{r_{k+1}^T r_{k+1}}{r_k^T r_k}$

In [16]:
x0 = np.matrix('1;1;1;1')
r0 = b - A * x0
p0 = r0

maxIter = 5
for it in range(maxIter):
    
    a0 = (r0.T * r0) / (p0.T * A * p0)
    
    x1 = x0 + a0[0,0] * p0
    r1 = r0 - a0[0,0] * A * p0
    
    if np.linalg.norm(r1) < 1E-8:
        break
        
    b0 = (r1.T * r1) / (r0.T * r0)
    p1 = r1 + b0[0,0] * p0
    
    r0 = r1
    p0 = p1
    x0 = x1

print(x0)

[[1.03200636]
 [0.63915819]
 [1.10532813]
 [2.20013736]]


## 해를 구해 봅시다 

\begin{equation}
\begin{bmatrix}
1 & 4 & 2 & 0 \\
9 & 5 & 0 & 0 \\
4 & 0 & 2 & 4 \\
6 & 1 & 8 & 3
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
15\\19\\26\\44
\end{bmatrix}
\end{equation}

In [21]:
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
b = np.array([15, 19, 26, 44])
print(A)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]


In [29]:
# matrix 타입을 이용하여 내적(dot product/inner product)을 편하게 구해도 되시고요..
# array 타입으로도 구현을 해보시면 좋겠죠?

x0 = np.array([1,1,1,1]) # 일벡터의 1차원 행렬
r0 = b - np.dot(A, x0)
p0 = r0

maxIter = 10000

for it in range(maxIter):
    a0 = np.dot(r0, r0) / np.dot( p0, np.dot(A, p0))
    x1 = x0 + a0 * p0
    r1 = r0 - a0 * np.dot(A, p0)
    
    if np.linalg.norm(r1) < 1e-8:
        break
        
    b0 = np.dot(r1, r1) / np.dot(r0, r0)
    p1 = r1 + b0 * p0
    
    r0 = r1
    p0 = p1
    x0 = x1

print(x0)

[0.98215476 2.01296542 3.0121475  4.01055586]


In [30]:
np.linalg.solve(A,b)

array([1., 2., 3., 4.])

# 고차원 선형방정식 풀이
- 직접 풀이 방식
- 반복적 풀이 방식
    - 야코비 방법
    - conjugated Gradient Method
    
## 수학적으로 깊이있게 다루진 않았지만 ...
- 고차원의 풀리지 않는 문제들에 대해서 선형방정식을 반복적으로 접근함으로 인해서 문제를 해결
- 선형방정식의 반복적인 계산으로 단순화 해서 문제를 해결
- 어쨋든 선형방정식을 풀어야 하는 문제는 남아있게 된다. 


## 복잡해 보이는 수식들에 대해서 너무 어려워 하지 않았으면 ... 